require "includes/inputparser"
describe("InputParser",function()
  describe("with person I",function()
    describe("with action magine",function()
      describe("without args",function()
        local text,subject,action,params=inputParser("i.magine()")
        it("should return i.magine() as the first argument",function()
          assert.are.same(text,"i.magine()")
          end)
        it("should return tony as the second argument",function()
          assert.are.same(subject,"tony")
          end)
        it("should return magine as the third argument",function()
          assert.are.same(action,"magine")
          end)
        it("should return {} as the fourth argument",function()
          assert.are.same(params,{})
          end)
        end)
      end)
    end)
  end)
