if not describe then
  names={}
  function describe(name,fn)
    table.insert(names,name)
    local index=#names
    fn()
    table.remove(names,index)
  end
  function it(name,fn)
    table.insert(names,name)
    local index=#names
    print(table.concat(names," "))
    table.remove(names,index)
  end
  assert={
    ["are"]={
      ["same"]=function()
      end
    }
  }
end
if not dreamcreature then
  require "dreamcreature"
end
describe("DreamCreature",function()
  describe("named furok",function()
    describe("with owner tony",function()
      thedreamcreature=dreamcreature("furok","tony")
      it("should have the owner \"tony\".",function()
        assert.are.same("tony",thedreamcreature.owner)
      end)
      it("should start in the Dream Plane.",function()
        assert.are.same(true,thedreamcreature.inDreamPlane)
      end)
      it("should have the creature name \"furok\".",function()
        assert.are.same("furok",thedreamcreature.creatureName)
      end)
      it("should have the catch phrase \"Let the fur fly!\".",function()
        assert.are.same("Let the fur fly!",thedreamcreature.catchPhrase)
      end)
      it("should have the type \"DreamCreature\".",function()
        assert.are.same("DreamCreature",thedreamcreature.type)
      end)
      it("should have no shields.",function()
        assert.are.same({},thedreamcreature.shields)
      end)
      it("should have the action tothedreamplane.",function()
        assert.are.same(thedreamcreature.actions.tothedreamlane,tothedreamplane)
      end)
      it("should have the action version.",function()
        assert.are.same(thedreamcreature.actions.version,version)
      end)
      it("should have the action help.",function()
        assert.are.same(thedreamcreature.actions.help,help)
      end)
      it("should have the function damage.",function()
        assert.are.same(thedreamcreature.damage,damage)
      end)
    end)
  end)
  describe("named ugger",function()
    describe("with owner edyn",function()
      thedreamcreature=dreamcreature("ugger","edyn")
      it("should have the owner \"edyn\".",function()
        assert.are.same("edyn",thedreamcreature.owner)
      end)
      it("should start in the Dream Plane.",function()
        assert.are.same(true,thedreamcreature.inDreamPlane)
      end)
      it("should have the creature name \"ugger\".",function()
        assert.are.same("ugger",thedreamcreature.creatureName)
      end)
      it("should have the catch phrase \"I am Ugger!\".",function()
        assert.are.same("I am Ugger!",thedreamcreature.catchPhrase)
      end)
      it("should have the type \"DreamCreature\".",function()
        assert.are.same("DreamCreature",thedreamcreature.type)
      end)
      it("should have no shields.",function()
        assert.are.same({},thedreamcreature.shields)
      end)
      it("should have the action tothedreamplane.",function()
        assert.are.same(thedreamcreature.actions.tothedreamlane,tothedreamplane)
      end)
      it("should have the action version.",function()
        assert.are.same(thedreamcreature.actions.version,version)
      end)
      it("should have the action help.",function()
        assert.are.same(thedreamcreature.actions.help,help)
      end)
      it("should have the function damage.",function()
        assert.are.same(thedreamcreature.damage,damage)
      end)
    end)
  end)
  describe("named freep",function()
    describe("with owner strag",function()
      thedreamcreature=dreamcreature("freep","strag")
      it("should have the owner \"strag\".",function()
        assert.are.same("strag",thedreamcreature.owner)
      end)
      it("should start in the Dream Plane.",function()
        assert.are.same(true,thedreamcreature.inDreamPlane)
      end)
      it("should have the creature name \"freep\".",function()
        assert.are.same("freep",thedreamcreature.creatureName)
      end)
      it("should have the catch phrase \"Whose noggin needs knockin'?\".",function()
        assert.are.same("Whose noggin needs knockin'?",thedreamcreature.catchPhrase)
      end)
      it("should have the type \"DreamCreature\".",function()
        assert.are.same("DreamCreature",thedreamcreature.type)
      end)
      it("should have no shields.",function()
        assert.are.same({},thedreamcreature.shields)
      end)
      it("should have the action tothedreamplane.",function()
        assert.are.same(thedreamcreature.actions.tothedreamlane,tothedreamplane)
      end)
      it("should have the action version.",function()
        assert.are.same(thedreamcreature.actions.version,version)
      end)
      it("should have the action help.",function()
        assert.are.same(thedreamcreature.actions.help,help)
      end)
      it("should have the function damage.",function()
        assert.are.same(thedreamcreature.damage,damage)
      end)
    end)
  end)
end)
